import Head from 'next/head';
import Chat from './chat';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Texting App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='initial-scale=1, width=device-width' />
      </Head>
      <Chat />
    </div>
  );
}
